version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: >
      sh -c "      
      cd ./fantasyteam &&
      echo 'Verifico se sono presenti aggiornamenti al database' &&
      python manage.py migrate &&
      echo 'Avvio app' &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - backend_data:/myfantasyteam-app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    volumes:
      - frontend_data:/myfantasyteam-app
    command: >
      sh -c "
      pwd &&
      ls -la &&      
      echo 'Lista dipendenze' &&
      npm list &&
      echo 'Avvio angular app' &&
      npm run start
      "
    ports:
      - "4200:4200"

volumes:
  backend_data:
  frontend_data: