version: "3"

services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
   
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
  
  adminer:
    container_name: adminer_postgres
    image: adminer:4.8.1
    restart: always
    ports:
      - 8000:8080