version: "3"

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
   
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db