# Generated by Django 3.2.12 on 2022-02-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('championshipId', models.AutoField(primary_key=True, serialize=False)),
                ('championshipName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('matchPlayed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sportId', models.AutoField(primary_key=True, serialize=False)),
                ('sportName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolleyballPlayer',
            fields=[
                ('volleyballPlayerid', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.IntegerField()),
                ('attackPoint', models.IntegerField()),
                ('forearmPass', models.IntegerField()),
                ('score', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volleyballplayer_player', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('teamAbbreviation', models.CharField(max_length=30)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship', to='api.championship')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('footballPlayerid', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('yellowCard', models.IntegerField()),
                ('redCard', models.IntegerField()),
                ('scoreAverage', models.FloatField()),
                ('fantaScoreAverage', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footballplayer_player', to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='api.sport'),
        ),
    ]
